import Sidebar from "./components/sidebar";
import Navbar from "./components/navbar";
import type { Metadata } from "next";
import { Henny_Penny } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const monsieur = Henny_Penny({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${monsieur.className} antialiased flex`}>
        <div className="flex-1">
          <Providers>
            <div className="flex">
              <div>
                <Sidebar />
              </div>
              <div className="w-full">
                <Navbar />
                {children}
              </div>
            </div>
          </Providers>
        </div>
      </body>
    </html>
  );
}
